// Single source of truth for where the project lives on GitHub.
export const GITHUB_REPO = "devian-labs/devian";
export const GITHUB_URL = `https://github.com/${GITHUB_REPO}`;
export const RELEASES_API_URL = `https://api.github.com/repos/${GITHUB_REPO}/releases`;
export const LATEST_RELEASE_URL = `${GITHUB_URL}/releases/latest`;
export const HOMEBREW_COMMANDS = [
    `brew tap devian-labs/devian ${GITHUB_URL}`,
    "brew install --cask devian-desktop",
];

// Used for canonical URLs, sitemap.xml, robots.txt and structured data.
export const SITE_URL = (process.env.NEXT_PUBLIC_APP_URL || "https://devian.app").replace(/\/+$/, "");
export const SITE_NAME = "Devian";
export const SITE_TITLE = "Devian: Free Desktop Control Center for AI Coding Agents";
export const SITE_DESCRIPTION =
    "Free, open-source desktop app for macOS, Windows and Linux. See what Claude Code, Codex, Cursor, OpenCode and Antigravity did, clean up and track tokens.";
export const THEME_COLOR = "#121212";

export const ORG_NAME = "Devian Labs";
export const ORG_URL = "https://devianlabs.com";
export const ORG_LOGO_URL = `${ORG_URL}/icon.png`;
export const ORG_GITHUB_URL = "https://github.com/devian-labs";

// Shared social images (generated by src/app/opengraph-image.tsx and twitter-image.tsx).
// Pages that set their own `openGraph`/`twitter` replace the root ones, so they reference these explicitly.
const OG_ALT = "Devian: stay in control of your AI coding agents";
export const OG_IMAGES = [{ url: "/opengraph-image", width: 1200, height: 630, alt: OG_ALT, type: "image/png" }];
export const TWITTER_IMAGES = [{ url: "/twitter-image", width: 1200, height: 630, alt: OG_ALT }];
